version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - DEBUG=1 curl -sSL https://download.sourceclear.com/ci.sh | bash
  build:
    commands:
      - mvn clean install
      - curl -sSL https://download.sourceclear.com/ci.sh | bash
